import GlassPanel from '../components/GlassPanel'
import SectionReveal from '../components/SectionReveal'
import useIsMobile from '../lib/useIsMobile'
import { MobileGlassCard } from '../components/mobile/MobileUIComponents'

const sections = [
  {
    title: 'Introduction',
    content: `This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://www.prarambhtheatre.com/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').`,
  },
  {
    title: 'Platform Ownership',
    content: `The Platform is owned by Prarambh, a theatre group registered with its office at Avenue 1, Gaur City 1, Gautam Buddha Nagar, Greater Noida West, Uttar Pradesh - 201318 (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').`,
  },
  {
    title: 'Acceptance of Terms',
    content: `Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transaction.

By mere use of the Platform, you shall be contracting with the Platform Owner and these terms and conditions including the policies constitute your binding obligations with the Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services').

Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect.

These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.`,
  },
  {
    title: 'User Definition',
    content: `For the purpose of these Terms of Use, wherever the context so requires 'you', 'your' or 'user' shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.

ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.`,
  },
  {
    title: 'Terms of Use',
    points: [
      'To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.',
      'Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.',
      'Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.',
      'The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.',
      'You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.',
      'You agree to pay us the charges associated with availing the Services, including but not limited to ticket booking fees for theatre shows.',
      'You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.',
      'You agree and acknowledge that the website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience to provide further information.',
    ],
  },
  {
    title: 'Binding Contract',
    content: `You understand that upon initiating a transaction for availing the Services (such as booking tickets for a theatre show) you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.`,
  },
  {
    title: 'Indemnification',
    content: `You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of your breach of this Terms of Use, Privacy Policy and other Policies, or your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.`,
  },
  {
    title: 'Force Majeure',
    content: `Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.`,
  },
  {
    title: 'Governing Law & Jurisdiction',
    content: `These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.

All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Gautam Buddha Nagar, Uttar Pradesh, India.`,
  },
  {
    title: 'Contact',
    content: `All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.

Point of Contact: Rabi Shankar Kar
Designation: Settlor / Senior Management Official
Contact: +91-9818620738, +91-9310109669
Available: Monday - Friday (9:00 AM - 6:00 PM)
Email: prarambh.theatre.group@gmail.com`,
  },
]

export default function TermsPage() {
  const isMobile = useIsMobile(640)

  if (isMobile) {
    return (
      <div className="px-4 pb-24">
        <header className="pt-6">
          <h1 className="font-serif text-2xl text-white">Terms & Conditions</h1>
          <p className="mt-2 text-sm text-white/60">Last updated: January 2026</p>
        </header>

        <section className="mt-5 space-y-4">
          {sections.map((section, idx) => (
            <MobileGlassCard key={idx}>
              <h2 className="font-serif text-lg text-white">{section.title}</h2>
              {section.content && (
                <p className="mt-3 text-sm leading-relaxed text-white/75 whitespace-pre-line">{section.content}</p>
              )}
              {section.points && (
                <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-relaxed text-white/75">
                  {section.points.map((point, i) => (
                    <li key={i}>{point}</li>
                  ))}
                </ol>
              )}
            </MobileGlassCard>
          ))}
        </section>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-4xl px-4 pb-16">
      <SectionReveal>
        <header className="pt-8 sm:pt-10">
          <h1 className="font-serif text-4xl text-white sm:text-5xl">Terms & Conditions</h1>
          <p className="mt-3 text-white/60">Last updated: January 2026</p>
        </header>
      </SectionReveal>

      <div className="mt-8 space-y-6">
        {sections.map((section, idx) => (
          <SectionReveal key={idx} delay={idx * 0.05}>
            <GlassPanel className="p-6 sm:p-8">
              <h2 className="font-serif text-xl text-white sm:text-2xl">{section.title}</h2>
              {section.content && (
                <p className="mt-4 text-sm leading-relaxed text-white/75 whitespace-pre-line sm:text-base">
                  {section.content}
                </p>
              )}
              {section.points && (
                <ol className="mt-4 list-decimal space-y-3 pl-5 text-sm leading-relaxed text-white/75 sm:text-base">
                  {section.points.map((point, i) => (
                    <li key={i}>{point}</li>
                  ))}
                </ol>
              )}
            </GlassPanel>
          </SectionReveal>
        ))}
      </div>
    </div>
  )
}
